#  ____                     __ _ _
# | __ ) _ __ _____      __/ _(_) | ___
# |  _ \| '__/ _ \ \ /\ / / |_| | |/ _ \
# | |_) | | |  __/\ V  V /|  _| | |  __/
# |____/|_|  \___| \_/\_/ |_| |_|_|\___|

brew "bat"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "curl"
brew "deno"
brew "docker"
brew "fd"
brew "ffmpeg"
brew "figlet"
brew "fortune"
brew "fzf"
brew "gh"
brew "git"
brew "gnupg"
brew "go" # brew's go is usually behind in version
brew "gtop"
brew "htop"
brew "imagemagick"
brew "jq"
brew "jump"
brew "lazygit"
brew "lolcat"

# not that I use any of these languages, but oh well
brew "lua-language"
brew "lua"
brew "luajit"
brew "luarocks"
brew "crystal"

brew "m-cli"
brew "make"
brew "mas"
brew "ncurses"
brew "neovim"
brew "ninja"
brew "node"
brew "pandoc"
brew "pnpm"
brew "qemu"
brew "ripgrep"
#brew "rust-analyzer" # only use when rustup doesn't have it
brew "sdl2"
brew "speedtest-cli"
brew "stow"
brew "supabase"
brew "thefuck"
brew "tmux"
brew "trash"
brew "tree-sitter"
brew "tree"
brew "tty-clock"
brew "tty-solitaire"
brew "wget"
brew "whalebrew"
brew "yt-dlp"
brew "zsh-fash-syntax-highlighting"
brew "zsh"

cask_args appdir: "~/Applications", require_sha: true

cask "alacritty"
cask "balenaetcher"
cask "basictex"
cask "boop"
cask "brave-browser"
cask "brewlet"
cask "coconutbattery"
cask "cool-retro-term"
cask "coteditor"
cask "discord"
cask "docker"
cask "fedora-media-writer"
cask "firefox"
cask "github"
cask "gitup"
#cask "google-chrome"
cask "handbrake"
cask "iina"
cask "minecraft"
cask "notion" # because I like to look productive
cask "numi"
cask "raycast"
cask "rectangle"
cask "spotify"
cask "ti-connect-ce"
cask "typora"
cask "typst"
cask "visual-studio-code"
cask "zulu"

tap "homebrew/cask-fonts"

cask "font-crimson-pro"
cask "font-fira-code"
cask "font-input"
cask "font-inter"
cask "font-iosevka-nerd-font"
cask "font-iosevka"
cask "font-jetbrains-mono-nerd-font"
cask "font-jetbrains-mono"
cask "font-lilex-nerd-font"
cask "font-lilex"
cask "font-lora"
cask "font-mohave"
cask "font-roboto-mono"
cask "font-roboto-slab"
cask "font-roboto"
cask "font-share-tech-mono"
cask "font-shure-tech-mono-nerd-font"
cask "font-syne-mono"
