general.import = ["/Users/tristanlukens/.config/alacritty/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.glyph_offset]
x = 0
y = 3

[font.normal]
family = "Lilex Nerd Font Mono"
style = "Regular"

[font.offset]
x = 1
y = 8

[terminal.shell]
#args = ["-l", "-c", "tmux"]
program = "/opt/homebrew/bin/zsh"

[window]
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 100
lines = 20

[window.padding]
x = 8
y = 3

[window.position]
x = 306
y = 309
